apiVersion: v1
kind: Service 
metadata: 
  labels:
    app: order-service
  name: order-service
  namespace: e-commerce
spec:  
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30107
  selector: 
    app: order-service