# Versi Api yang didefinisikan
apiVersion: apps/v1
# jenis Object Kubernetes (deployment)
kind: Deployment
# Metadata untuk deployment
metadata:
  #  Nama Deployment
  name: karsajobs-frontend
# Spesifikasi untuk deployment
spec:
  # Jumlah replika pod yang akan dibuat
  replicas: 1
  # selector untuk memilih pod
  selector:
    # Pod yang dipilih harus memiliki label sesuai ketentuan
    matchLabels:
      app: frontend
  # Template untuk membuat pod
  template:
    # Metadata untuk pod
    metadata:
      # Label pod
      labels:
        app: frontend
    # Spesifikasi untuk pod
    spec:
      # Konfigurasi container dalam pod
      containers:
      # Nama Kontainer
      - name: karsajobs-ui
        # Image yang digunakan untuk membuat container
        image: ghcr.io/fahram/karsajobs-ui:latest
        # Mekanisme pull image (image dipull setiap kali pod dimulai)
        imagePullPolicy: Always
        # Sumber Daya yang dibutuhkan oleh penampung ini
        resources:
          # jumlah maksimum sumber daya komputasi yang diperbolehkan
          limits:
            # Ukuran CPU yang akan digunakan. "250m" berarti hanya menggunakan 1/4 dari ukuran CPU
            cpu: "250m"
            # Memori/RAM yang akan digunakan. "256Mi" berarti 256 Megabyte
            memory: "256Mi"
        # Port yang digunakan
        ports:
        # port yang digunakan untuk mengakses container
        - containerPort: 8000
        # Environment variable yang dibutuhkan oleh aplikasi
        env:
        - name: VUE_APP_BACKEND
          value: 'http://192.168.49.2:30627'
