version: 2.1

orbs:
  docker: circleci/docker@2.2.0
  go: circleci/go@1.7.3
jobs:
  # proses jobs untuk test-app backend
  test-app:
    executor:
      name : go/default 
      tag: '1.15'
    steps:
      - checkout
      - run:
          name: Run Unit Test
          command: go test -v -short --count=1 $(go list ./...)
  # build docker file dan push ke ghcr
  build-app-karsajobs:
    executor:
      name: docker/docker
      environment:
        IMAGE_NAME: ghcr.io/fahram/karsajobs:latest
    # steps dari setiap jobs, tidak dikomen karena sudah ada di name
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Login to ghcr.io
          command: echo $PASSWORD_GITHUB | docker login ghcr.io -u fahram --password-stdin
      - run:
          name: Publish Image to ghcr.io
          command: docker push $IMAGE_NAME:latest

workflows:
  ci:
    jobs:
      - docker/hadolint:
          dockerfiles: './Dockerfile'
      - test-app
      - build-app-karsajobs:
          requires: 
            - docker/hadolint
            - test-app
    