apiVersion: v1
kind: Service 
metadata: 
  namespace: e-commerce
  labels:
    app: shipping-service
  name: shipping-service
spec: 
  type: NodePort
  ports:
  - port: 3001
    nodePort: 30108
  selector: 
    app: shipping-service