apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv
  labels:
    type: local
  namespace: e-commerce
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/rabbitmq/mnesia"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  namespace: e-commerce
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi