apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: e-commerce
spec:
  selector:
    app: rabbitmq
  type: NodePort
  ports:
    - name: amqp
      port: 5672
      protocol: TCP
      targetPort: 5672
      nodePort: 30104
    - name: http
      port: 15672
      protocol: TCP
      targetPort: 15672
      nodePort: 30105
    - name: prometheus
      port: 15692
      protocol: TCP
      targetPort: 15692
      nodePort: 30106